#!/usr/bin/env python3
"""Generate docker-compose.yml for a corporate-shaped federation topology.

Inputs (env vars):
  FED_SCHEME: federation wire scheme (h2 | h2s | webtransport)
  FED_PORT  : federation wire port (must match the scheme)

Topology — 17 bridges modelling a tiered enterprise network:

                EDGE1   EDGE2                          ← DMZ (2 bridges)
                  │ \\   / │
                  │  \\ /  │
                  │   X   │
                  │  / \\  │
            DC1 ──┴── DC2 ──┴── DC3                   ← Backbone (3, full mesh)
             │         │         │
        HUB-EAST   HUB-CENTRAL   HUB-WEST             ← Regional hubs (3)
       ╱   │   ╲   ╱   │   ╲   ╱   │   ╲
     BE1  BE2  BE3 BC1 BC2 BC3 BW1 BW2 BW3            ← Branches (9)

Federation edges (24 total):
  * DC mesh (3):                  DC1-DC2, DC1-DC3, DC2-DC3
  * DMZ uplinks (4):              EDGE1-DC1, EDGE1-DC2,
                                  EDGE2-DC2, EDGE2-DC3
  * Hub uplinks (6):              HUB-EAST-DC1, HUB-EAST-DC2,
                                  HUB-CENTRAL-DC2, HUB-CENTRAL-DC3,
                                  HUB-WEST-DC1, HUB-WEST-DC3
  * Branch uplinks (9):           BE1/2/3-HUB-EAST,
                                  BC1/2/3-HUB-CENTRAL,
                                  BW1/2/3-HUB-WEST

Worst-case path: BE1 ↔ BW1 = 4 hops (BE1 → HUB-EAST → DC1 → HUB-WEST → BW1).
This is right at the `max_announce_hops=4` default ceiling — the test
verifies the federation works at maximum depth without resorting to
reactive FindPeer fallback.

Each bridge runs a drift-mosh-server (representing local services like
file servers / internal apps). 6 clients distributed across branches
dial every non-local server (96 cross-bridge dials total).

Image is reused from docker/federation-discovery/Dockerfile. Subnet
10.57.0.0/24 (avoids clashing with pentagon/topology tests).
"""
import os
import sys


# ─── Topology definition ──────────────────────────────────────────
# Bridge names ordered by tier so the YAML reads top-down.
BRIDGES = [
    # DMZ (2)
    "edge1", "edge2",
    # Backbone (3)
    "dc1", "dc2", "dc3",
    # Regional hubs (3)
    "hub-east", "hub-central", "hub-west",
    # Branches (9)
    "be1", "be2", "be3",
    "bc1", "bc2", "bc3",
    "bw1", "bw2", "bw3",
]

# Symmetric federation edges (undirected). Both ends get a
# `--federate` flag pointing at the other.
EDGES = [
    # DC full mesh.
    ("dc1", "dc2"), ("dc1", "dc3"), ("dc2", "dc3"),
    # DMZ uplinks.
    ("edge1", "dc1"), ("edge1", "dc2"),
    ("edge2", "dc2"), ("edge2", "dc3"),
    # Hub uplinks.
    ("hub-east", "dc1"), ("hub-east", "dc2"),
    ("hub-central", "dc2"), ("hub-central", "dc3"),
    ("hub-west", "dc1"), ("hub-west", "dc3"),
    # Branch uplinks.
    ("be1", "hub-east"), ("be2", "hub-east"), ("be3", "hub-east"),
    ("bc1", "hub-central"), ("bc2", "hub-central"), ("bc3", "hub-central"),
    ("bw1", "hub-west"), ("bw2", "hub-west"), ("bw3", "hub-west"),
]

# Clients live on branches; servers live on every bridge.
# Choose clients spread across geographies to stress the longest paths.
CLIENTS = ["c-be1", "c-be3", "c-bc1", "c-bc3", "c-bw1", "c-bw3"]
CLIENT_HOME_BRIDGE = {
    "c-be1": "be1", "c-be3": "be3",
    "c-bc1": "bc1", "c-bc3": "bc3",
    "c-bw1": "bw1", "c-bw3": "bw3",
}


# ─── IP plan (10.57.0.0/24) ───────────────────────────────────────
BRIDGE_BASE = 11    # bridges:  10.57.0.11–.27
SERVER_BASE = 41    # servers:  10.57.0.41–.57
CLIENT_BASE = 81    # clients:  10.57.0.81–.86


def bridge_ip(name: str) -> str:
    return f"10.57.0.{BRIDGE_BASE + BRIDGES.index(name)}"


def server_ip(bridge: str) -> str:
    return f"10.57.0.{SERVER_BASE + BRIDGES.index(bridge)}"


def client_ip(client: str) -> str:
    return f"10.57.0.{CLIENT_BASE + CLIENTS.index(client)}"


def federates_for(bridge: str) -> list[str]:
    out = []
    for a, b in EDGES:
        if a == bridge:
            out.append(b)
        elif b == bridge:
            out.append(a)
    return out


def normalize_pubvar(name: str) -> str:
    """`hub-east` → `PUB_HUB_EAST` for compose-substituted env vars."""
    return "PUB_" + name.upper().replace("-", "_")


def main() -> None:
    scheme = os.environ.get("FED_SCHEME", "h2s")
    port = os.environ.get("FED_PORT", "51827")

    out = []
    out.append("# Auto-generated by gen-compose.py — do not hand-edit.")
    out.append(f"# Topology: corporate ({len(BRIDGES)} bridges, "
               f"{len(EDGES)} federation edges)")
    out.append(f"# Wire: {scheme}://...:{port}")
    out.append("")
    out.append("x-base-build: &base-build")
    out.append("  build:")
    out.append("    context: ../..")
    out.append("    dockerfile: docker/federation-discovery/Dockerfile")
    out.append("")
    out.append("services:")

    # ── Bridges ──
    for b in BRIDGES:
        peers = federates_for(b)
        fed_lines = "".join(
            f"\n        --federate {scheme}://{bridge_ip(p)}:{port}@"
            f"${{{normalize_pubvar(p)}}}"
            for p in peers
        )
        out.append(
            f"""  bridge-{b}:
    <<: *base-build
    container_name: corp-bridge-{b}
    networks:
      corpnet:
        ipv4_address: {bridge_ip(b)}
    environment:
      RUST_LOG: "info,drift=info"
    volumes:
      - ./identities:/identities:ro
    command: >
      drift --identity /identities/{b}.key bridge
        --listen udp://0.0.0.0:51820
        --listen {scheme}://0.0.0.0:{port}{fed_lines}
"""
        )

    # ── Servers — one per bridge ──
    for b in BRIDGES:
        out.append(
            f"""  server-{b}:
    <<: *base-build
    container_name: corp-server-{b}
    depends_on: [ bridge-{b} ]
    networks:
      corpnet:
        ipv4_address: {server_ip(b)}
    environment:
      RUST_LOG: "info,drift_mosh_server=info"
    volumes:
      - ./identities:/identities:ro
    command: >
      drift-mosh-server
        --identity-file /identities/s-{b}.hex
        --bridge udp://{bridge_ip(b)}:51820@${{{normalize_pubvar(b)}}}
        --shell /bin/sh
"""
        )

    # ── Clients — one per chosen branch ──
    server_deps = ", ".join(f"server-{b}" for b in BRIDGES)
    for c in CLIENTS:
        out.append(
            f"""  client-{c}:
    <<: *base-build
    container_name: corp-client-{c}
    depends_on: [ {server_deps} ]
    networks:
      corpnet:
        ipv4_address: {client_ip(c)}
    volumes:
      - ./identities:/identities:ro
      - ./inventory-{c}:/etc/drift:ro
    command: ["sleep", "infinity"]
"""
        )

    out.append("networks:")
    out.append("  corpnet:")
    out.append("    driver: bridge")
    out.append("    ipam:")
    out.append("      config:")
    out.append("        - subnet: 10.57.0.0/24")

    sys.stdout.write("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
