#!/usr/bin/env python3
"""Generate docker-compose.yml for a 5-bridge federation topology.

Inputs (env vars):
  TOPOLOGY  : one of {mesh, ring, star, chain}
  FED_SCHEME: federation wire scheme (h2 | h2s | webtransport)
  FED_PORT  : federation wire port (must match the scheme)

Outputs docker-compose.yml on stdout. Same image / container-naming /
client-server-bridge attach pattern as docker/federation-pentagon —
only the federation edges differ per topology.

Topologies (B1..B5 = bridges 1..5):

  mesh  — K5 complete graph (every pair federated): 10 edges
  ring  — 5-cycle: B1-B2-B3-B4-B5-B1 (5 edges; opposite vertices
          need 2-hop forwarding)
  star  — B1 is hub; B2/B3/B4/B5 each federate to B1 only:
          4 edges (B2-B5 reach each other only via B1)
  chain — linear: B1-B2-B3-B4-B5 (4 edges; B1<->B5 needs 4 hops)

Federation is symmetric: each declared edge becomes a --federate
in both directions (just like the existing federation-triangle
and federation-pentagon tests).
"""
import os
import sys

BRIDGES = ["b1", "b2", "b3", "b4", "b5"]
BRIDGE_IPS = {
    "b1": "10.56.0.11",
    "b2": "10.56.0.12",
    "b3": "10.56.0.13",
    "b4": "10.56.0.14",
    "b5": "10.56.0.15",
}
SERVER_IPS = {
    "s1": "10.56.0.21",
    "s2": "10.56.0.22",
    "s3": "10.56.0.23",
    "s4": "10.56.0.24",
    "s5": "10.56.0.25",
}
CLIENT_IPS = {
    "c1": "10.56.0.31",
    "c2": "10.56.0.32",
    "c3": "10.56.0.33",
    "c4": "10.56.0.34",
    "c5": "10.56.0.35",
}


def topology_edges(name: str) -> list[tuple[str, str]]:
    """Return the (undirected) edge list for a named topology."""
    if name == "mesh":
        return [(a, b) for i, a in enumerate(BRIDGES) for b in BRIDGES[i + 1 :]]
    if name == "ring":
        return [
            (BRIDGES[i], BRIDGES[(i + 1) % len(BRIDGES)])
            for i in range(len(BRIDGES))
        ]
    if name == "star":
        return [(BRIDGES[0], b) for b in BRIDGES[1:]]
    if name == "chain":
        return [(BRIDGES[i], BRIDGES[i + 1]) for i in range(len(BRIDGES) - 1)]
    raise SystemExit(f"unknown topology: {name}")


def federates_for(bridge: str, edges: list[tuple[str, str]]) -> list[str]:
    """All bridges this bridge has a federation link to (both directions)."""
    out = []
    for a, b in edges:
        if a == bridge:
            out.append(b)
        elif b == bridge:
            out.append(a)
    return out


def main() -> None:
    topology = os.environ.get("TOPOLOGY", "mesh")
    scheme = os.environ.get("FED_SCHEME", "h2s")
    port = os.environ.get("FED_PORT", "51827")

    edges = topology_edges(topology)

    # Emit YAML
    lines = []
    lines.append("# Auto-generated by gen-compose.py — do not hand-edit.")
    lines.append(f"# Topology: {topology}  Wire: {scheme}://...:{port}")
    lines.append(f"# Edges ({len(edges)}): " + ", ".join(f"{a}-{b}" for a, b in edges))
    lines.append("")
    lines.append("x-base-build: &base-build")
    lines.append("  build:")
    lines.append("    context: ../..")
    lines.append("    dockerfile: docker/federation-discovery/Dockerfile")
    lines.append("")
    lines.append("services:")

    # Bridges (literal indentation — no dedent gymnastics)
    for bridge in BRIDGES:
        bridge_ip = BRIDGE_IPS[bridge]
        peers = federates_for(bridge, edges)
        fed_lines = "".join(
            f"\n        --federate {scheme}://{BRIDGE_IPS[p]}:{port}@${{PUB_{p.upper()}}}"
            for p in peers
        )
        lines.append(
            f"""  bridge-{bridge}:
    <<: *base-build
    container_name: top-bridge-{bridge}
    networks:
      topnet:
        ipv4_address: {bridge_ip}
    environment:
      RUST_LOG: "info,drift=info"
    volumes:
      - ./identities:/identities:ro
    command: >
      drift --identity /identities/{bridge}.key bridge
        --listen udp://0.0.0.0:51820
        --listen {scheme}://0.0.0.0:{port}{fed_lines}
"""
        )

    # Servers
    for i, server in enumerate(["s1", "s2", "s3", "s4", "s5"], start=1):
        bridge = BRIDGES[i - 1]
        lines.append(
            f"""  server-{server}:
    <<: *base-build
    container_name: top-server-{server}
    depends_on: [ bridge-{bridge} ]
    networks:
      topnet:
        ipv4_address: {SERVER_IPS[server]}
    environment:
      RUST_LOG: "info,drift_mosh_server=info"
    volumes:
      - ./identities:/identities:ro
    command: >
      drift-mosh-server
        --identity-file /identities/{server}.hex
        --bridge udp://{BRIDGE_IPS[bridge]}:51820@${{PUB_{bridge.upper()}}}
        --shell /bin/sh
"""
        )

    # Clients
    server_deps = ", ".join(f"server-{s}" for s in ["s1", "s2", "s3", "s4", "s5"])
    for i, client in enumerate(["c1", "c2", "c3", "c4", "c5"], start=1):
        lines.append(
            f"""  client-{client}:
    <<: *base-build
    container_name: top-client-{client}
    depends_on: [ {server_deps} ]
    networks:
      topnet:
        ipv4_address: {CLIENT_IPS[client]}
    volumes:
      - ./identities:/identities:ro
      - ./inventory-{client}:/etc/drift:ro
    command: ["sleep", "infinity"]
"""
        )

    lines.append("networks:")
    lines.append("  topnet:")
    lines.append("    driver: bridge")
    lines.append("    ipam:")
    lines.append("      config:")
    lines.append("        - subnet: 10.56.0.0/24")

    sys.stdout.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
