//! TOML config for `drift-vpn`. Layout intentionally mirrors
//! WireGuard's `[Interface]` / `[Peer]` mental model so users
//! coming from WG can transfer their config knowledge:
//!
//!     [interface]
//!     identity_file = "/etc/drift-vpn/identity.key"
//!     address       = "10.0.0.1/24"
//!     listen        = "udp://0.0.0.0:51820"
//!     mtu           = 1380
//!
//!     [[peer]]
//!     public_key  = "abcdef..."           # 64 hex chars
//!     allowed_ips = ["10.0.0.2/32"]       # CIDR list
//!     endpoint    = "udp://198.51.100.7:51820"   # optional
//!     keepalive   = 25                    # seconds, optional
//!
//! Differences from WireGuard (deliberate, listed for clarity):
//!
//! - `endpoint` and `listen` are full DRIFT URLs, so multi-
//!   transport (`tcp://`, `tls://`, `ws://`, `http://`,
//!   `onion://`) "just works" from the same config shape.
//! - A peer with no `endpoint` is reachable only via mesh —
//!   another peer announces them. (Future feature; v0.1
//!   requires endpoint.)

use anyhow::{anyhow, Context, Result};
use ipnet::IpNet;
use serde::Deserialize;
use std::path::{Path, PathBuf};

#[derive(Debug, Deserialize)]
pub struct Config {
    pub interface: Interface,
    #[serde(default, rename = "peer")]
    pub peers: Vec<Peer>,
}

#[derive(Debug, Deserialize)]
pub struct Interface {
    /// Path to a 64-char hex file containing the 32-byte
    /// X25519 secret. Generated by `drift-vpn keygen`.
    pub identity_file: PathBuf,
    /// Local tun-device address as `<ip>/<prefix>` (e.g.
    /// `10.0.0.1/24`).
    pub address: IpNet,
    /// DRIFT URL to bind. Single-string form for v0.1; future
    /// versions will accept an array for multi-transport.
    pub listen: String,
    /// Tun device MTU. Default 1380 leaves room for DRIFT
    /// short-header overhead inside a 1500-byte UDP frame.
    #[serde(default = "default_mtu")]
    pub mtu: u32,
    /// Optional name for the tun device (Linux only). Default
    /// is kernel-assigned (`tun0`, `tun1`, …).
    #[serde(default)]
    pub name: Option<String>,
}

fn default_mtu() -> u32 {
    1380
}

#[derive(Debug, Deserialize)]
pub struct Peer {
    /// Peer's static X25519 pubkey, 64 hex chars.
    pub public_key: String,
    /// CIDR ranges this peer "owns" — outbound packets whose
    /// destination IP falls in any of these route to this peer.
    pub allowed_ips: Vec<IpNet>,
    /// DRIFT URL to dial for first-contact. Optional in mesh
    /// scenarios (where the peer is reached via another peer's
    /// announcement); required in v0.1.
    pub endpoint: Option<String>,
    /// Periodic keepalive interval in seconds. Sends a tiny
    /// padding packet so NATs don't time out the path. Default
    /// off.
    pub keepalive: Option<u64>,
}

impl Peer {
    pub fn pubkey_bytes(&self) -> Result<[u8; 32]> {
        let raw = hex::decode(&self.public_key)
            .with_context(|| format!("invalid hex pubkey {:?}", self.public_key))?;
        if raw.len() != 32 {
            return Err(anyhow!(
                "pubkey must be 32 bytes (64 hex chars), got {}",
                raw.len()
            ));
        }
        let mut k = [0u8; 32];
        k.copy_from_slice(&raw);
        Ok(k)
    }
}

impl Config {
    pub async fn load(path: &Path) -> Result<Self> {
        let body = tokio::fs::read_to_string(path)
            .await
            .with_context(|| format!("reading {}", path.display()))?;
        let cfg: Config = toml::from_str(&body)
            .with_context(|| format!("parsing TOML config {}", path.display()))?;
        cfg.validate()?;
        Ok(cfg)
    }

    fn validate(&self) -> Result<()> {
        for (i, p) in self.peers.iter().enumerate() {
            p.pubkey_bytes()
                .with_context(|| format!("peer #{}", i))?;
            if p.allowed_ips.is_empty() {
                return Err(anyhow!(
                    "peer #{} ({}) has no allowed_ips — VPN can't route to it",
                    i,
                    &p.public_key[..16.min(p.public_key.len())]
                ));
            }
        }
        Ok(())
    }
}
