//! TOML config for `drift-vpn`. Layout intentionally mirrors
//! WireGuard's `[Interface]` / `[Peer]` mental model so users
//! coming from WG can transfer their config knowledge:
//!
//!     [interface]
//!     identity_file = "/etc/drift-vpn/identity.key"
//!     address       = "10.0.0.1/24"
//!     listen        = "udp://0.0.0.0:51820"
//!     mtu           = 1380
//!
//!     [[peer]]
//!     public_key  = "abcdef..."           # 64 hex chars
//!     allowed_ips = ["10.0.0.2/32"]       # CIDR list
//!     endpoint    = "udp://198.51.100.7:51820"   # optional
//!     keepalive   = 25                    # seconds, optional
//!
//! Differences from WireGuard (deliberate, listed for clarity):
//!
//! - `endpoint` and `listen` are full DRIFT URLs, so multi-
//!   transport (`tcp://`, `tls://`, `ws://`, `http://`,
//!   `onion://`) "just works" from the same config shape.
//! - A peer with no `endpoint` is reachable only via mesh —
//!   another peer announces them. (Future feature; v0.1
//!   requires endpoint.)

use anyhow::{anyhow, Context, Result};
use ipnet::IpNet;
use serde::Deserialize;
use std::path::{Path, PathBuf};

/// Deserializer for fields that accept either `"udp://..."`
/// (back-compat single form) or `["udp://...", "tls://..."]`
/// (v0.2 array form). After parsing, the field is always a
/// `Vec<String>` — callers don't need to handle two shapes.
fn one_or_many<'de, D>(deserializer: D) -> std::result::Result<Vec<String>, D::Error>
where
    D: serde::Deserializer<'de>,
{
    #[derive(Deserialize)]
    #[serde(untagged)]
    enum Helper {
        One(String),
        Many(Vec<String>),
    }
    Ok(match Helper::deserialize(deserializer)? {
        Helper::One(s) => vec![s],
        Helper::Many(v) => v,
    })
}

fn one_or_many_opt<'de, D>(deserializer: D) -> std::result::Result<Option<Vec<String>>, D::Error>
where
    D: serde::Deserializer<'de>,
{
    one_or_many(deserializer).map(Some)
}

#[derive(Debug, Deserialize)]
pub struct Config {
    pub interface: Interface,
    #[serde(default, rename = "peer")]
    pub peers: Vec<Peer>,
    /// Runtime auto-failover (v0.4) tuning. Optional — defaults
    /// give every multi-endpoint peer health-driven failover
    /// without thrashing on noisy WAN.
    #[serde(default)]
    pub failover: Failover,
}

/// Per-daemon failover policy. Applied to every peer with two
/// or more endpoints. Single-endpoint peers ignore the policy
/// entirely (nowhere to fail over to).
///
/// Defaults are tuned for "WAN that mostly works" — slow enough
/// not to react to transient blips, fast enough to recover from
/// a real outage in tens of seconds.
#[derive(Debug, Deserialize, Clone)]
pub struct Failover {
    /// How often the supervisor wakes up to check peer health.
    /// Lower = faster reaction; higher = less wakeup overhead.
    /// Default 2s.
    #[serde(default = "default_check_interval_ms")]
    pub check_interval_ms: u64,
    /// A peer is considered unhealthy if no AEAD-valid traffic
    /// has arrived from it in this many seconds. With the
    /// default 5s ping interval that's two missed pings worth
    /// of silence. Default 10s.
    #[serde(default = "default_stale_secs")]
    pub stale_secs: u64,
    /// After a failover, hold on the new endpoint for this many
    /// seconds before considering another switch. Prevents
    /// ping-pong when the primary briefly recovers. Default 30s.
    #[serde(default = "default_hold_secs")]
    pub hold_secs: u64,
    /// If non-zero: switch endpoints when SRTT exceeds
    /// `rtt_multiplier × baseline` for several consecutive
    /// samples. Default 0 (disabled). Opt-in because RTT
    /// thrashing on real WAN is easy to misconfigure.
    #[serde(default)]
    pub rtt_multiplier: f32,
    /// Hard kill switch. Set to false in the [failover] section
    /// to disable the supervisor for all peers. Default true.
    #[serde(default = "default_true")]
    pub enabled: bool,
}

impl Default for Failover {
    fn default() -> Self {
        Self {
            check_interval_ms: default_check_interval_ms(),
            stale_secs: default_stale_secs(),
            hold_secs: default_hold_secs(),
            rtt_multiplier: 0.0,
            enabled: true,
        }
    }
}

fn default_check_interval_ms() -> u64 { 2_000 }
fn default_stale_secs() -> u64 { 10 }
fn default_hold_secs() -> u64 { 30 }
fn default_true() -> bool { true }

#[derive(Debug, Deserialize)]
pub struct Interface {
    /// Path to a 64-char hex file containing the 32-byte
    /// X25519 secret. Generated by `drift-vpn keygen`.
    pub identity_file: PathBuf,
    /// Local tun-device address as `<ip>/<prefix>` (e.g.
    /// `10.0.0.1/24`).
    pub address: IpNet,
    /// DRIFT URL(s) to bind. v0.2 accepts an array of URLs for
    /// multi-transport — `["udp://0.0.0.0:51820", "tls://0.0.0.0:443"]`
    /// — so one daemon serves clients on whichever wire works
    /// for their network. Single-string form is back-compat.
    #[serde(deserialize_with = "one_or_many")]
    pub listen: Vec<String>,
    /// Tun device MTU. Default 1340 — that's `drift::MAX_PAYLOAD`
    /// (1348) minus an 8-byte safety margin, so TCP segments
    /// emitted at full MTU still fit inside DRIFT's per-packet
    /// payload limit. Setting a higher MTU here will silently
    /// drop large TCP segments (`send_data` returns
    /// PacketTooShort) — visible as TCP retransmit storms even
    /// while UDP works fine.
    #[serde(default = "default_mtu")]
    pub mtu: u32,
    /// Optional name for the tun device (Linux only). Default
    /// is kernel-assigned (`tun0`, `tun1`, …).
    #[serde(default)]
    pub name: Option<String>,
}

fn default_mtu() -> u32 {
    // drift::MAX_PAYLOAD == 1348 (1400 packet - 36 header - 16
    // tag). We give 8 bytes of margin so a full-MTU TCP
    // segment from the kernel always fits.
    1340
}

#[derive(Debug, Deserialize)]
pub struct Peer {
    /// Peer's static X25519 pubkey, 64 hex chars.
    pub public_key: String,
    /// CIDR ranges this peer "owns" — outbound packets whose
    /// destination IP falls in any of these route to this peer.
    pub allowed_ips: Vec<IpNet>,
    /// DRIFT URL to dial for first-contact (back-compat single
    /// form). Either `endpoint` OR `endpoints` must be set in
    /// v0.2; mesh-only peers (no endpoint) land in v0.4.
    pub endpoint: Option<String>,
    /// v0.2 array form. Tried in priority order — first to land
    /// a session wins. UDP first, TLS / WS / HTTP / Tor as
    /// fallbacks for hostile networks.
    #[serde(default, deserialize_with = "one_or_many_opt")]
    pub endpoints: Option<Vec<String>>,
    /// Periodic keepalive interval in seconds. Sends a tiny
    /// padding packet so NATs don't time out the path. Default
    /// off.
    pub keepalive: Option<u64>,
}

impl Peer {
    pub fn pubkey_bytes(&self) -> Result<[u8; 32]> {
        let raw = hex::decode(&self.public_key)
            .with_context(|| format!("invalid hex pubkey {:?}", self.public_key))?;
        if raw.len() != 32 {
            return Err(anyhow!(
                "pubkey must be 32 bytes (64 hex chars), got {}",
                raw.len()
            ));
        }
        let mut k = [0u8; 32];
        k.copy_from_slice(&raw);
        Ok(k)
    }

    /// Resolve `endpoint` (single, v0.1) and `endpoints` (array,
    /// v0.2) into one prioritized list. The single form, if
    /// present, is treated as the highest-priority entry; the
    /// array follows.
    pub fn endpoint_list(&self) -> Vec<String> {
        let mut out = Vec::new();
        if let Some(s) = &self.endpoint {
            out.push(s.clone());
        }
        if let Some(eps) = &self.endpoints {
            for url in eps {
                // De-dup: don't add `endpoint` again if it's
                // already in `endpoints`.
                if !out.contains(url) {
                    out.push(url.clone());
                }
            }
        }
        out
    }
}

impl Config {
    pub async fn load(path: &Path) -> Result<Self> {
        let body = tokio::fs::read_to_string(path)
            .await
            .with_context(|| format!("reading {}", path.display()))?;
        let cfg: Config = toml::from_str(&body)
            .with_context(|| format!("parsing TOML config {}", path.display()))?;
        cfg.validate()?;
        Ok(cfg)
    }

    fn validate(&self) -> Result<()> {
        if self.interface.listen.is_empty() {
            return Err(anyhow!("interface.listen must contain at least one URL"));
        }
        for (i, p) in self.peers.iter().enumerate() {
            p.pubkey_bytes()
                .with_context(|| format!("peer #{}", i))?;
            if p.allowed_ips.is_empty() {
                return Err(anyhow!(
                    "peer #{} ({}) has no allowed_ips — VPN can't route to it",
                    i,
                    &p.public_key[..16.min(p.public_key.len())]
                ));
            }
            if p.endpoint_list().is_empty() {
                return Err(anyhow!(
                    "peer #{} ({}) has no endpoint or endpoints — v0.2 requires at least one",
                    i,
                    &p.public_key[..16.min(p.public_key.len())]
                ));
            }
        }
        Ok(())
    }
}
